### ISSUE TITLE
1.18.2 marked on a 1.18.1-only jar

### ISSUE THREAD

**Issue by CDAGaming** [sokratis12GR/ArmorPlus#259]
Not sure if this was a time issue or whatnot, but the ArmorPlus jar marked for 1.18.2 fails due to the refactors made in 1.18.2

**Comment by CDAGaming** [comment]
```
Caught exception during event RegistryEvent.Register<minecraft:block> dispatch for modid armorplus
java.lang.NoClassDefFoundError: net/minecraft/tags/Tag$Named
	at TRANSFORMER/armorplus@1.18.1-18.0.4-beta/com.sofodev.armorplus.registry.blocks.castle.StoneBrickStairsBlock.<clinit>(StoneBrickStairsBlock.java:40)
	at TRANSFORMER/armorplus@1.18.1-18.0.4-beta/com.sofodev.armorplus.registry.ModBlocks.lambda$static$10(ModBlocks.java:68)
```

**Comment by sokratis12GR** [comment]
Thanks for that, it seems to be related to a tag registry change in one of the latest forge versions on top of 1.18.2 changes.
Oh well, next release will be 1.18.2 targeted only. ~either later today (Sunday) or sometime tomorrow, will provide another comment once the release is published.

**Comment by sokratis12GR** [comment]
Also unmarked the version as supported.

**Comment by sokratis12GR** [comment]
Alrighty, [ArmorPlus 1.18.2-18.0.5-beta](https://www.curseforge.com/minecraft/mc-mods/armorplus/files/3719363) should fix the 
compatibility issues and work with 1.18.2.

**Comment by CDAGaming** [comment]
Thank you!

**Comment by sokratis12GR** [comment]
Thanks for reporting the issue, if there are any other issues will try to fix them as well.
